version: '3'

services:
    zookeeper:
        build: ./zookeeper
        container_name: kafka-starter-zookeeper
        restart: always
        ports:
            - "2181:2181"

    kafka:
        build: ./kafka
        container_name: kafka-starter-kafka
        restart: always
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
